name: Build Next.js web app
on: push
jobs:
  build-project:
    name: Build build-project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install NPM dependencies
      run: npm install
    - name: Build project assets
      run: npm run build
    - name: Upload static site content
      uses: actions/upload-artifact@v3
      with:
        name: static-site
        path: .next/
  release-project:
    name: Release project
    permissions: write-all    #This is key if cloning as template from existing repo
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: static-site
      - name: Test artifact download
        run: ls -R
      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
          filename: site.zip
      - name: Create Github Release
        id: create_new_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload-url: ${{ steps.create_new_release.outputs.upload.url }}
          asset_path: ./site.zip
          asset_name: site-v${{ github.run_number }}.zip
          asset_content_type: appplication/zip
       