name: Build Next.js web app
on: push
jobs:
  build-project:
    name: Build build-project
    runs-on: ubuntu-latest
    steps:
    - name: CHeckout code
      uses: actions/checkout@v3
    - name: Install NPM dependencies
      run: npm install
    - name: Build project assets
      run: npm run build
